---

###################
# Install tomcat on nodes
###################
- hosts: vm-debian-3
  become: yes
  roles:
    - role: openjdk8
    - role: tomcat
      tomcat_iptables_enabled: True
      tomcat_load_balancing_enabled: True
      tomcat_network_interface: "enp0s8"
      tags: ['tomcat']

- hosts: vm-debian-2
  become: yes
  roles:
    - role: openjdk8
    - role: tomcat
      tomcat_iptables_enabled: True
      tomcat_load_balancing_enabled: True
      tomcat_network_interface: "enp0s8"
      tags: ['tomcat']


###################
# Install apache2
###################
- hosts: vm-debian-1
  become: yes
  roles:
    - role: apache2_private_ca
    - role: apache2
      tags: ['apache2']