---

###################
# Playbook to install role tomcat
###################
- hosts: vm-debian-1
  become: yes
  roles:
    - role: tomcat
      tomcat_goss_enabled: True
      tomcat_iptables_enabled: True
      tomcat_openssl_enabled: False
      tomcat_keystore_enabled: True
      tomcat_network_interface: "enp0s8"
      tags: ['tomcat']