---
# tasks file for apache2

- include_tasks: install.yml

- include_tasks: config.yml

- include_tasks: modsecurity.yml

- include_tasks: ssl.yml
  when: apache2_vhost_https_enabled

- include_tasks: mod_jk.yml

- include_tasks: status.yml

- name: Restart apache2
  command: echo "Restart apache2"
  notify:
    - Restart apache2