---
# handlers file for tomcat
- name: Reload systemd
  systemd:
    daemon-reload: yes

- name: Enable Tomcat service
  systemd:
    name: tomcat
    enabled: yes

- name: Restart tomcat
  systemd:
    name: tomcat
    state: restarted