---
# defaults file for apache_vhosts_mod_jk

http_default_port: 80
https_default_port: 443
apache_home: /opt/apache2
java_home: /usr/bin/java
apache_vhosts_dir: "{{ apache_home }}/vhosts"
apache_logs_dir: "/var/log/apache2"
apache_conf_dir: "{{ apache_home }}/conf"
apache_httpd_file: "{{ apache_conf_dir }}/httpd.conf"
apache_ssl_dir: "/etc/pki/apache"
apache_ssl_ca_dir: "{{ apache_ssl_dir }}/private_ca"
root_user: root
root_group: sys
mod_jk_port: '8009'
apache_server_admin: admin@example.com
apache_conf_log_level: warn
apache_vhosts_conf_dir: "{{ apache_conf_dir }}/vhosts"
ssl_country: FR
ssl_state: Rhone
ssl_locality: Lyon
ssl_organisation: Syscom
ssl_organisation_unit: IT
apache_vhosts_mod_jk:
  vhost1:
    serverName: 'vhosts1.fr'
    serverAlias: 'www.vhosts1.fr'
    https_enabled: True
    ssl_subj: "/C=\"{{ ssl_country }}\"/ST=\"{{ ssl_state }}\"/L=\"{{ ssl_locality }}\"/O=\"{{ ssl_organisation }}\"/OU=\"{{ ssl_organisation_unit }}\"/CN=vhosts1.fr"
    webapps: 'docs'
    workers:
        - { name: 'worker1', host: '192.168.57.2', port: '{{ mod_jk_port }}' }
        - { name: 'worker2', host: '192.168.58.2', port: '{{ mod_jk_port }}' }